use std::fs::{File, OpenOptions};
use std::io::{Write, BufWriter};
use std::path::Path;

use clap::Command;

use crate::core::model::SchemaSection;
use crate::core::{
    error::MDMError, model::{CliCommand, CommandCtx}
};

const COMMAND_NAME: &str = "build";
const COMMAND_ABOUT: &str = "Combine the sections into the output file";
const COMMAND_LONG_ABOUT: &str = "Iterates over all the sections folder path recursively and appends their contents to the output file on the specified order";

pub struct BuildCommand {}

impl BuildCommand {
    fn sync_sections(
        writer: &mut BufWriter<File>,
        sections: &[SchemaSection],
        base_path: &Path,
        depth: usize,
    ) -> Result<(), MDMError> { 
        for section in sections {
            let current_path: std::path::PathBuf = base_path.join(section.get_fs_name());
            if !current_path.exists() {
                let reason = format!(
                    "'{}' was not found inside the sections folder",
                    current_path.to_string_lossy(),
                );
                return Err(MDMError::InvalidCommandState {
                    reason,
                    help: "Try running 'mdm sync' to create missing files".into(),
                });
            }/*  */

            let header = section.get_section_header(depth);
            writeln!(writer, "{}\n", header)
                .map_err(|err| MDMError::from_io(err, &current_path))?;

            let read_path = if section.is_leaf() {
                Some(current_path.clone())
            } else if section.has_intro {
                Some(current_path.join("intro.md"))
            } else {
                None
            };

            if let Some(path) = read_path {
                let mut file = File::open(&path)
                    .map_err(|err| MDMError::from_io(err, &path))?;
                std::io::copy(&mut file, writer)
                    .map_err(|err| MDMError::Other(err.to_string()))?;
                writer.write_all(b"\n\n")
                    .map_err(|err| MDMError::Other(err.to_string()))?;
            };

            BuildCommand::sync_sections(
                writer, &section.children, &current_path, depth + 1
            )?;
        }
        Ok(())
    }
}

impl CliCommand for BuildCommand {
    fn name(&self) -> &str {
        COMMAND_NAME
    }

    fn requires_paths(&self) -> bool {
        true
    }

    fn build(&self) -> Command {
        return Command::new(COMMAND_NAME)
            .about(COMMAND_ABOUT)
            .long_about(COMMAND_LONG_ABOUT);
    }

    fn run(&self, ctx: CommandCtx) -> Result<(), MDMError> {
        let config = ctx.require_config()?;
        let schema = config.require_schema(
            "Cannot build output file without a defined schema",
            "Define a schema and ensure files are generated by running 'mdm sync sections'"
        )?;
        let sections_path = config.paths.sections.as_ref();
        let output_file = match OpenOptions::new()
            .truncate(true)
            .create(true)
            .write(true)
            .open(&config.paths.output) {
                Ok(output) => output,
                Err(e) => Err(MDMError::IO {
                    source: e,
                    path: config.paths.output.clone(),
                })?
            };
        let mut writer = BufWriter::new(output_file);
        BuildCommand::sync_sections(
            &mut writer, &schema, &sections_path, 1
        )?;
        println!("Successfully combined document at '{}'", config.paths.output.display());
        Ok(())
    }
}