paths:
  schema_path: "./schema.yaml"
  sections_folder: "./sections"
  assets_folder: "./assets"
  output_path: "./document.md"

vars:
  author: "My Team's Name"
  repo_url: "github.com/mygithub/project-documentation"